version: "3.8"

services:
  reverse-proxy:
    image: public.ecr.aws/docker/library/traefik:latest
    command: --api --docker
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  unit:
    build:
      context: ../
      dockerfile: ./.devops/app.Dockerfile
    ports:
      - "80:8080"
    labels:
      - "traefik.frontend.rule=Host:demo.docker.localhost"